[package]
name = "eoss-fuse"
version = "0.1.0"
authors = [ "lightsing <light.tsing@gmail.com>" ]
edition = "2018"

[dependencies]
blake3 = "0.3.7"
fuser = "0.7"
hex = "0.4.2"
once_cell = "1.5.2"
parking_lot = "0.11"
rand = "0.8"
thiserror = "1.0.23"
tokio = "1.5"
