[package]
name = "eoss-fuse"
version = "0.1.0"
authors = ["lightsing <light.tsing@gmail.com>"]
edition = "2018"

[dependencies]
fuser = "0.7"
parking_lot = "0.11"
tokio = "1.5"
rand = "0.8"
once_cell = "1.5.2"
crossbeam = "0.8.0"
hex = "0.4.2"
